server.port=8084
spring.application.name=bi-service

erp.service.url=http://localhost:8081
crm.service.url=http://localhost:8082
supplychain.service.url=http://localhost:8083

jwt.secret=digitrans-secret-key-for-jwt-token-generation-2024-agrocam-sa
jwt.expiration=86400000

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
